### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by NKU-ZiXuan** [kosmastsk/panda_kinematics_solver#1]
Hi，I get a compile issus when I input `catkin_make` in the terminator.
![2020-07-20 07-50-26屏幕截图](https://user-images.githubusercontent.com/49083996/87879147-7a1efb80-ca1b-11ea-99c6-1f9f92e05b98.png)
It seems that It is ralated to eigen3, but i don't know how to correct. Can you give me some help？ thank you！

**Comment by kosmastsk** [comment]
How did you install Eigen in your pc?

**Comment by NKU-ZiXuan** [comment]
> How did you install Eigen in your pc?

sudo apt-get install libeigen3-dev

**Comment by kosmastsk** [comment]
Could you please try the instructions from [here](https://answers.ros.org/question/253181/howto-eigen-installation/) and try again? 

I am using Eigen 3.3.4 in ROS Melodic for the specific package.

**Comment by NKU-ZiXuan** [comment]
I tried again, but it doesn't work. The problem is the same as previous. [This line](https://github.com/kosmastsk/panda_kinematics_solver/blob/master/src/ik_fk_calculator.cpp#L70) in your code looks like something wrong. `_kinematic_state->getGlobalLinkTransform` function returns `Eigen::Affine3d`, while you defined  `end_effector_state` as `Eigen::Isometry3d` type.

**Comment by kosmastsk** [comment]
If you check on the melodic version of moveit_core, [here](https://github.com/ros-planning/moveit/blob/melodic-devel/moveit_core/robot_state/include/moveit/robot_state/robot_state.h#L1442) you can see that this function returns an `Eigen::Isometry3d` type. In other version of it, it returns Eigen::Affine3d.
Try to install `ros-melodic-moveit-core` and see if that fixes your bug
